services:
  backend:
    build:
      context: ./backend
      dockerfile: ../docker/Dockerfile.backend
    restart: always
    env_file:
      - ./backend/.env
    ports:
      - '3001:3001'
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: ../docker/Dockerfile.frontend
    restart: always
    ports:
      - '3000:3000'
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
